version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my_network
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 4000:4000
    networks:
      - my_network

networks:
  my_network:
  
