export const All_PROBLEMS_REQUEST = 'All_PROBLEMS_REQUEST';
export const All_PROBLEMS_SUCCESS = 'All_PROBLEMS_SUCCESS';
export const All_PROBLEMS_FAIL = 'All_PROBLEMS_FAIL';

export const PROBLEM_DETAILS_REQUEST = 'PROBLEM_DETAILS_REQUEST';
export const PROBLEM_DETAILS_SUCCESS = 'PROBLEM_DETAILS_SUCCESS';
export const PROBLEM_DETAILS_FAIL = 'PROBLEM_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS'