export const All_PROBLEMS_REQUEST = 'All_PROBLEMS_REQUEST';
export const All_PROBLEMS_SUCCESS = 'All_PROBLEMS_SUCCESS';
export const All_PROBLEMS_FAIL = 'All_PROBLEMS_FAIL';

export const PROBLEM_DETAILS_REQUEST = 'PROBLEM_DETAILS_REQUEST';
export const PROBLEM_DETAILS_SUCCESS = 'PROBLEM_DETAILS_SUCCESS';
export const PROBLEM_DETAILS_FAIL = 'PROBLEM_DETAILS_FAIL';

export const NEW_PROBLEM_REQUEST = 'NEW_PROBLEM_REQUEST';
export const NEW_PROBLEM_SUCCESS = 'NEW_PROBLEM_SUCCESS';
export const NEW_PROBLEM_RESET = 'NEW_PROBLEM_RESET';
export const NEW_PROBLEM_FAIL = 'NEW_PROBLEM_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS'