export const NEW_TESTCASE_REQUEST = 'NEW_TESTCASE_REQUEST';
export const NEW_TESTCASE_SUCCESS = 'NEW_TESTCASE_SUCCESS';
export const NEW_TESTCASE_RESET = 'NEW_TESTCASE_RESET';
export const NEW_TESTCASE_FAIL = 'NEW_TESTCASE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';